### ISSUE TITLE
mat1 x mat2 error

### ISSUE THREAD

**Issue by youyuanyi** [jankolf/ser-fiq-pytorch#3]
My input image size is 512x512
```
- [ ] Traceback (most recent call last):
- [ ]   File "/home/dell/workspace/pycharmProject/eva_exp/evaluations/ser-fiq-pytorch-main/main.py", line 34, in <module>
- [ ]     scores = resnet.calculate_serfiq(image, T=10, scaling=5.0)
- [ ]   File "/home/dell/anaconda3/envs/eva/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
- [ ]     return func(*args, **kwargs)
- [ ]   File "/home/dell/workspace/pycharmProject/eva_exp/evaluations/ser-fiq-pytorch-main/backbones/iresnet.py", line 205, in calculate_serfiq
- [ ]     x = self.fc(x)
- [ ]   File "/home/dell/anaconda3/envs/eva/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
- [ ]     return forward_call(*args, **kwargs)
- [ ]   File "/home/dell/anaconda3/envs/eva/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
- [ ]     return F.linear(input, self.weight, self.bias)
- [ ] RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x524288 and 25088x512)
```

And is the results same as the https://github.com/pterhoer/FaceImageQuality?

**Comment by jankolf** [comment]
Hi,
the ResNet uses a variable fc_scale to specify the size of the linear layer.
Currently fc_scale is set to 7*7, as this is the image size at the last conv layers when an 112x112 image is used as input.
Therefore, the linear layer expects an input size of 512 (filters) x 7 (w) x 7 (h)  = 25088.
Because your image inputs are bigger, you have to change the fc_scale variable in line 83 ([here](https://github.com/jankolf/ser-fiq-pytorch/blob/d08893ea5fdb92b094381413a120c866f78f8c90/backbones/iresnet.py#L83)).
I assume you have to set it to 1024, and the output size at this conv layer is 512x32x32:
`L83: fc_scale = 32 * 32`

The results are not the same as the linked repo, as in this project we have used a different pre-trained network with MXNet.
This project uses the same architecture, but a different pre-trained network and therefore different weights.

Hope this helps.

Best,
Jan

**Comment by youyuanyi** [comment]
Thank you! I change the fc_scale to 32*32,but it still doesn't work:
```
Traceback (most recent call last):
  File "/home/dell/workspace/pycharmProject/eva_exp/evaluations/ser-fiq-pytorch-main/main.py", line 27, in <module>
    resnet.load_state_dict(
  File "/home/dell/anaconda3/envs/eva/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IResNet:
	size mismatch for fc.weight: copying a param with shape torch.Size([512, 25088]) from checkpoint, the shape in current model is torch.Size([512, 524288]).
```

**Comment by jankolf** [comment]
Hi,
as the weights/matrix sizes are changed the pre-trained backbone can not be used.
If you want to run 500x500 images you have to train the model yourself and than use the SER-FIQ approach.
If you want to use the pre-trained model you have to resize your images to 112x112.

Best,
Jan
